### ISSUE TITLE
Can SLIMM provide report on sub species?

### ISSUE THREAD

**Issue by zhangqunyuan** [seqan/slimm#15]
For example, in the taxonomy  file names.dmp, regarding species Acidithiobacillus ferrooxidans, there are two sub species ( Acidithiobacillus ferrooxidans ATCC 23270 and ATCC 53993), I have two questions: (1) besides Acidithiobacillus ferrooxidans, can SLIMM provide report on Acidithiobacillus ferrooxidans ATCC 23270 and Acidithiobacillus ferrooxidans ATCC 53993, separately?  (2) if some reads are aligned/assigned to sub species ATCC 23270, some to sub species ATCC 53993, some to species Acidithiobacillus ferrooxidans, how the coverage for species Acidithiobacillus ferrooxidans reported in the file sorted_species_reported.tsv is calculated? 

Thanks,

Qunyuan Zhang (qunyuan@gmail.com)

**Comment by temehi** [comment]
Hi Qunyuan Zhang,

Thanks for your interest in using SLIMM.

> Can SLIMM provide report on sub species?

Unfortunately NO! But we are working on a newer version of SLIMM which will include sub-species level reporting. 

>  if some reads are aligned/assigned to sub species ATCC 23270, some to sub species ATCC 53993, some to species Acidithiobacillus ferrooxidans, how the coverage for species Acidithiobacillus ferrooxidans reported in the file sorted_species_reported.tsv is calculated?

This is done by taking the union of the reads which are mapped to any of the sub-species of a given species excluding reads that are also mapped to genomes of other species. We use the resulting number of reads and an average genome length of the sub species to calculate the coverage.

**Comment by temehi** [comment]
I will close this issue now. If you have more questions on this you may reopen it.
