### ISSUE TITLE
Custom Database Questions

### ISSUE THREAD

**Issue by feltzmc** [seqan/slimm#17]
Thank you for updating the directions on building a custom database.  I notice that your options allow for building a database with all refseq Bacterica, Archaea and Viruses, but does not include fungi or other eukaryotes.  Two questions:

1. Would it be possible to include fungi as an option in the pre-processing scripts?

2. I am interested in building a custom database from NT, how would one go about doing so?

Thanks,
Matt

**Comment by temehi** [comment]
Hi Matt,

1. There is no similar way to include fungi like Bacterica, Archaea and Viruses. if you take a look at the [readme file ](ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxcat_readme.txt) of ncbi taxcat you could clearly see that there is no category for fungi. A work around would be to add the taxonomic ids of fungi as a comma separated list in addition to the A,B and V categories. 

2. The download script will try to download only the best available genome for an organism. This way it's non-redundant. At the moment there is no way to use the NR directly. you can only choose between RefSeq and GeenBank.

**Comment by temehi** [comment]
@feltzmc I will close the issue now. Feel free to reopen it, if your question is not answered.
