### ISSUE TITLE
build from source locally

### ISSUE THREAD

**Issue by danfulop** [seqan/slimm#18]
I want to suggest that you add information for building SLIMM from source locally (i.e. without root access). Following the instructions here (http://seqan.readthedocs.io/en/master/Infrastructure/Use/FindSeqAnCMake.html#) I was able to figure out I needed to use 2 cmake options for it to build, e.g.:

```
cmake ../slimm/src \
-DCMAKE_PREFIX_PATH="$HOME/bin/applications/seqan/util/cmake" \
-DSEQAN_INCLUDE_PATH="$HOME/bin/applications/seqan/include"
```

**Comment by temehi** [comment]
Thanks for your suggestion! I will update the wiki accordingly. 
But you can also use the SeqAn that comes with the source code as suggested in your issue #19 .
