### ISSUE TITLE
problem building from source

### ISSUE THREAD

**Issue by danfulop** [seqan/slimm#19]
I ran `cmake` just fine, but then ran into a problem when running `make`:

- This worked fine:

```
$ cmake ../slimm/src -DCMAKE_PREFIX_PATH="$HOME/bin/applications/seqan/util/cmake" -DSEQAN_INCLUDE_PATH="$HOME/bin/applications/seqan/include"
```

- But, then I got this error in the next step:

```
$ make
Scanning dependencies of target slimm
make[2]: Warning: File `CMakeFiles/slimm.dir/depend.make' has modification time 40 s in the future
[ 50%] Building CXX object CMakeFiles/slimm.dir/slimm.o
<command-line>:0:19: error: too many decimal points in number
/data/home/dfulop/bin/applications/slimm/src/slimm.h:592:24: note: in expansion of macro 'SEQAN_APP_VERSION'
     setVersion(parser, SEQAN_APP_VERSION);
                        ^
make[2]: *** [CMakeFiles/slimm.dir/slimm.o] Error 1
make[1]: *** [CMakeFiles/slimm.dir/all] Error 2
make: *** [all] Error 2
```

It seems a bit odd that this would happen, that is that it would fail due to SeqAn's version. I installed SeqAn with Linuxbrew, but the seqan dir pointed to in the cmake flags is a downloaded source. However, it's the same version number as the Linuxbrew-installed seqan.

**Comment by temehi** [comment]
I would highly recommend using the SeqAn provided with the source code as a sub-repository. You can do that by cloning the SLIMM git repository **recursively** as follows:

`git clone  --recursive git@github.com:seqan/slimm.git`

then:
```
mkdir slimm-build
cd slimm-build
cmake -DCMAKE_CXX_FLAGS="-std=c++14" -DCMAKE_BUILD_TYPE=Release ../slimm
make
```

**Comment by danfulop** [comment]
Okay. I might try that. Thanks for the suggestion and the prompt feedback! In the end I used the RPM package and installed SLIMM locally (to my user) with the help of `rpm2cpio`. I'm using it in a shared cluster in which I don't have sudo permission.
