### ISSUE TITLE
empty taxonomic profiles

### ISSUE THREAD

**Issue by danfulop** [seqan/slimm#20]
I am getting **empty** taxonomic profiles out of SLIMM, despite the reference filtering step preserving 100 or more taxa (more or less depending on parameters). I am puzzled as to how I should adjust parameters to get SLIMM to work. I am adjusting the parameters that make sense to me from reading your manuscript, namely --bin-width, --min-reads, and --cov-cutoff.

Any advice in terms of troubleshooting, QC, and/or parameter settings would be greatly appreciated!

Here's one example stdout from my data:

```
Reading 1 of 6 files ...
SWT1_S36_microbe_mapped.bam
computing features of each reference genome ...
in 0 secs [OK!]

Analysing alignments, reads and references ...
  124865015 records processed.
    39820109 matching reads
    25279026 uniquily matching reads
in 738 secs

Number of Ref with reads = 4363
Expected Coverage = 0.374302
Coverage Cutoff = 0.00156425 (0.999 quantile)
UniqCoverage Cutoff = 0.000161812 (0.999 quantile)
Filtering unlikely sequences ...
  441 passed the threshould coverage.
  1217 ref's couldn't pass the coverage threshould.
  3905 ref's couldn't pass the uniq coverage threshould.
  Uniquily matching reads increased from 25279026 to 25455761
in 45 secs [OK!]

Writing features to a file ...
in 0 secs [OK!]

Assigning reads to Least Common Ancestor (LCA)
in 36 secs [OK!]

Writing taxnomic profile(s) ...
        species level: 0 bellow cutoff (0.001) ...
          genus level: 0 bellow cutoff (0.001) ...
         family level: 0 bellow cutoff (0.001) ...
          order level: 0 bellow cutoff (0.001) ...
          class level: 0 bellow cutoff (0.001) ...
         phylum level: 0 bellow cutoff (0.001) ...
   superkingdom level: 0 bellow cutoff (0.001) ...
in 0 secs [OK!]
```

**Comment by danfulop** [comment]
It seems as though the problem is that all taxa had a `RelAbundanceUniq2` = 0.
I ran SLIMM one more time with these parameters (different params. than above): `--bin-width=50000 --min-reads 10000 --mapping-files $ref_dir --cov-cutoff 0.99999`.

Attached is the "raw" table sorted by `RelAbundance` in descending order. What jumps out at me is that `RelAbundanceUniq2` = 0 for all taxa, even the ones with high relative abundance.

Do you have any suggestions for troubleshooting this?  Thanks in advance for your help!!

The data are PE 100, human gut samples.
[SWT1_S36_microbe_mapped.txt](https://github.com/seqan/slimm/files/1445037/SWT1_S36_microbe_mapped.txt)

**Comment by temehi** [comment]
Hi,

Did you find a solution for your problem?  Is that why you closed this issue? 

It's a bug, but not a harmful one :), that `RelAbundance2` is always 0. 

But your empty taxonomic profiles are I think related to the slimm mapping database you are using/missing (`-m` parameter). It was not able to map the references to Species, genus etc ...  

you can get one from:
http://ftp.mi.fu-berlin.de/pub/dadi/slimm/slimmDB_5K.zip

**Comment by danfulop** [comment]
Yeah, I was mistakenly using the Yara index as the SLIMM DB. Simple error. Good to know that there's an `-m` flag to indicate that!
